version: '3.8' # Specifies the version of Docker Compose

services:
  db:
    image: postgres:14 # Uses the official PostgreSQL image
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data # Persists database data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: scaffold_app_development

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b 0.0.0.0"
    volumes:
      - .:/app # Mounts the current directory to the container
    ports:
      - "3000:3000" # Maps port 3000 on the host to port 3000 in the container
    depends_on:
      - db # Ensures the database service starts before the web service
    environment:
      DATABASE_HOST: localhost
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: scaffold_app_development

volumes:
  postgres-data:
